name: Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to provision (dev|staging|prod)'
        required: true
        default: 'dev'
      ref:
        description: 'Git and docker tag (can be a commit SHA).'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Choose environment
        id: choose-environment
        uses: actions/github-script@v3
        with:
          script: |
            const mapEventToEnvironment = () => {
              if (context.eventName === 'deployment_status' && context.payload.deployment_status.state == 'success' && context.payload.deployment_status.environment == 'dev') return { "environment": 'staging', "ref": context.payload.deployment.ref };
              if (context.eventName === 'workflow_dispatch') return { "environment": context.payload.inputs.environment, "ref": context.payload.inputs.ref };
              return { "environment": undefined, "ref": undefined };
            };
            const { environment, ref } = mapEventToEnvironment();
            core.setOutput('environment', environment);
            core.setOutput('ref', ref);

      - name: Start VAEC deployment
        uses: actions/github-script@v3
        if: ${{ steps.choose-environment.outputs.environment }}
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ steps.choose-environment.outputs.ref }}',
              environment: '${{ steps.choose-environment.outputs.environment }}',
              required_contexts: [],
              auto_merge: false,
            });
