name: Load test (SMS Response Time)

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The target environment (dev|staging|perf)"
        required: true
        default: "dev"
      commit_sha:
        type: string
        description: "The commit SHA containing code you want to load test"
        required: true
      run_time:
        type: string
        description: "Stop after the specified amount of time, e.g. (300s, 20m, 3h, 1h30m, etc.)"
        required: true
        default: "10s"
      num_users:
        type: string
        description: "Number of concurrent Locust users."
        required: true
        default: "1"
      spawn_rate:
        type: string
        description: "The rate per second in which users are spawned."
        required: true
        default: "1"
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "The target environment (dev|staging|perf)"
        required: true
        default: "perf"
      commit_sha:
        type: string
        description: "The commit SHA containing code you want to load test"
        required: true
      run_time:
        type: string
        description: "Stop after the specified amount of time, e.g. (300s, 20m, 3h, 1h30m, etc.)"
        required: true
        default: "10s"
      num_users:
        type: string
        description: "Number of concurrent Locust users."
        required: true
        default: "1"
      spawn_rate:
        type: string
        description: "The rate per second in which users are spawned."
        required: true
        default: "1"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure VAEC AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
      - name: Invoke load test
        uses: ./.github/actions/run-commands-on-ec2
        with:
          instance-id-ssm-parameter-path: /utility/locust/instance
          commands: >-
            "sudo su - locust -c \"cd notification-api && git checkout origin main && git pull --all && git checkout ${{ inputs.commit_sha }} &>/dev/null\"",
            "sudo su - locust -c \"locust -f notification-api/load_testing/send_sms_load_test.py --headless -u ${{ inputs.num_users }} -r ${{ inputs.spawn_rate }} --host https://${{ inputs.environment }}.api.notifications.va.gov --run-time ${{ inputs.run_time }} --csv results 2>/dev/null\"",
            "sudo su - locust -c \"cat results_stats.csv\""
