name: Load test (Email Delivery Time)

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The target environment (dev|staging|perf)"
        required: true
        default: "dev"
      commit_sha:
        type: string
        description: "The commit SHA containing code you want to load test"
        required: true
      email_limit:
        type: string
        description: "Number of emails to send"
        required: true
        default: "10"
      email_status_query_interval:
        type: string
        description: "Number of seconds to wait between requests to query notification status"
        required: true
        default: "1"
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "The target environment (dev|staging|perf)"
        required: true
        default: "perf"
      commit_sha:
        type: string
        description: "The commit SHA containing code you want to load test"
        required: true
      email_limit:
        type: string
        description: "Number of emails to send"
        required: true
        default: "10"
      email_status_query_interval:
        type: string
        description: "Number of seconds to wait between requests to query notification status"
        required: true
        default: "1"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure VAEC AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1
          role-to-assume: ${{ secrets.VAEC_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
      - name: Invoke load test
        uses: ./.github/actions/run-commands-on-ec2
        with:
          instance-id-ssm-parameter-path: /utility/locust/instance
          commands: >-
            "sudo su - locust -c \"cd notification-api && git checkout origin master && git pull --all && git checkout ${{ inputs.commit_sha }} &>/dev/null\"",
            "sudo su - locust -c \"locust -f notification-api/load_testing/send_email_load_test.py --headless --host https://${{ inputs.environment }}.api.notifications.va.gov --email-limit ${{ inputs.email_limit }} --email-status-query-interval ${{ inputs.email_status_query_interval }} --csv results_email 2>/dev/null\"",
            "sudo su - locust -c \"cat results_email_stats.csv\""
