name: Tag push to Perf
on:
  push:
    tags:
      - "v*"

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      git-tag: ${{ steps.tag.outputs.version }}
    steps:
      - name: Get the version
        id: tag
        run: |
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Env Values
        run: |
          echo "The environment is Perf"
          echo "The commit tag is ${{ steps.tag.outputs.version }}"

  run-build:
    needs: [setup-env]
    uses: ./.github/workflows/build.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit

  run-lambda-deploy:
    needs: [setup-env]
    uses: ./.github/workflows/lambda-functions.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
      lambdaName: "All"
    secrets: inherit

  run-deployment:
    needs: [setup-env, run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit
